before:
  hooks:
    - go mod tidy
builds:
  -
    env:
      - CGO_ENABLED=1
    id: "yubikey-agent"
    main: ./
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

brews:
  -
    name: sandstorm-yubikey-agent

    tap:
      owner: sandstorm
      name: homebrew-tap

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: Sandstorm Release Bot
      email: release-bot@sandstorm.de

    # Folder inside the repository to put the formula.
    # Default is the root folder.
    folder: Formula

    # Your app's homepage.
    # Default is empty.
    homepage: "https://github.com/sandstorm/yubikey-agent"

    # modelled after https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/yubikey-agent.rb
    custom_block: |
      def post_install
        (var/"run").mkpath
        (var/"log").mkpath
      end

      def caveats
        <<~EOS
          To use this SSH agent, add the config to ~/.ssh/config:

            Host *
              IdentityAgent #{var}/run/yubikey-agent.sock
        EOS
      end

      service do
        run [opt_bin/"yubikey-agent", "-l", var/"run/yubikey-agent.sock"]
        keep_alive true
        log_path var/"log/yubikey-agent.log"
        error_log_path var/"log/yubikey-agent.log"
      end

      test do
        socket = testpath/"yubikey-agent.sock"
        fork { exec bin/"yubikey-agent", "-l", socket }
        sleep 1
        assert_predicate socket, :exist?
      end